export interface CountryConfig {
    code: string;
    name: string;
    language: string;
    phonePrefix: string;
}

export const COUNTRIES: CountryConfig[] = [
    // Afrique
    { code: 'DZ', name: 'Algeria', language: 'fr', phonePrefix: '213' },
    { code: 'AO', name: 'Angola', language: 'fr', phonePrefix: '244' },
    { code: 'BJ', name: 'Bénin', language: 'fr', phonePrefix: '229' },
    { code: 'BW', name: 'Botswana', language: 'en', phonePrefix: '267' },
    { code: 'BF', name: 'Burkina Faso', language: 'fr', phonePrefix: '226' },
    { code: 'BI', name: 'Burundi', language: 'fr', phonePrefix: '257' },
    { code: 'CM', name: 'Cameroun', language: 'fr', phonePrefix: '237' },
    { code: 'CV', name: 'Cape Verde', language: 'fr', phonePrefix: '238' },
    { code: 'CF', name: 'Centrafrique', language: 'fr', phonePrefix: '236' },
    { code: 'TD', name: 'Tchad', language: 'fr', phonePrefix: '235' },
    { code: 'KM', name: 'Comoros', language: 'fr', phonePrefix: '269' },
    { code: 'CG', name: 'Congo', language: 'fr', phonePrefix: '242' },
    { code: 'CD', name: 'Congo (RDC)', language: 'fr', phonePrefix: '243' },
    { code: 'CI', name: 'Côte d\'Ivoire', language: 'fr', phonePrefix: '225' },
    { code: 'DJ', name: 'Djibouti', language: 'fr', phonePrefix: '253' },
    { code: 'EG', name: 'Egypt', language: 'en', phonePrefix: '20' },
    { code: 'GQ', name: 'Equatorial Guinea', language: 'fr', phonePrefix: '240' },
    { code: 'ER', name: 'Eritrea', language: 'en', phonePrefix: '291' },
    { code: 'SZ', name: 'Eswatini', language: 'en', phonePrefix: '268' },
    { code: 'ET', name: 'Ethiopia', language: 'en', phonePrefix: '251' },
    { code: 'GA', name: 'Gabon', language: 'fr', phonePrefix: '241' },
    { code: 'GM', name: 'Gambia', language: 'en', phonePrefix: '220' },
    { code: 'GH', name: 'Ghana', language: 'en', phonePrefix: '233' },
    { code: 'GN', name: 'Guinea', language: 'fr', phonePrefix: '224' },
    { code: 'GW', name: 'Guinea-Bissau', language: 'fr', phonePrefix: '245' },
    { code: 'KE', name: 'Kenya', language: 'en', phonePrefix: '254' },
    { code: 'LS', name: 'Lesotho', language: 'en', phonePrefix: '266' },
    { code: 'LR', name: 'Liberia', language: 'en', phonePrefix: '231' },
    { code: 'LY', name: 'Libya', language: 'en', phonePrefix: '218' },
    { code: 'MG', name: 'Madagascar', language: 'fr', phonePrefix: '261' },
    { code: 'MW', name: 'Malawi', language: 'en', phonePrefix: '265' },
    { code: 'ML', name: 'Mali', language: 'fr', phonePrefix: '223' },
    { code: 'MR', name: 'Mauritania', language: 'fr', phonePrefix: '222' },
    { code: 'MU', name: 'Mauritius', language: 'en', phonePrefix: '230' },
    { code: 'YT', name: 'Mayotte', language: 'fr', phonePrefix: '262' },
    { code: 'MA', name: 'Morocco', language: 'fr', phonePrefix: '212' },
    { code: 'MZ', name: 'Mozambique', language: 'en', phonePrefix: '258' },
    { code: 'NA', name: 'Namibia', language: 'en', phonePrefix: '264' },
    { code: 'NE', name: 'Niger', language: 'fr', phonePrefix: '227' },
    { code: 'NG', name: 'Nigeria', language: 'en', phonePrefix: '234' },
    { code: 'RE', name: 'Réunion', language: 'fr', phonePrefix: '262' },
    { code: 'RW', name: 'Rwanda', language: 'en', phonePrefix: '250' },
    { code: 'SH', name: 'Saint Helena', language: 'en', phonePrefix: '290' },
    { code: 'ST', name: 'Sao Tome and Principe', language: 'fr', phonePrefix: '239' },
    { code: 'SN', name: 'Sénégal', language: 'fr', phonePrefix: '221' },
    { code: 'SC', name: 'Seychelles', language: 'en', phonePrefix: '248' },
    { code: 'SL', name: 'Sierra Leone', language: 'en', phonePrefix: '232' },
    { code: 'SO', name: 'Somalia', language: 'en', phonePrefix: '252' },
    { code: 'ZA', name: 'South Africa', language: 'en', phonePrefix: '27' },
    { code: 'SS', name: 'South Sudan', language: 'en', phonePrefix: '211' },
    { code: 'SD', name: 'Sudan', language: 'en', phonePrefix: '249' },
    { code: 'TZ', name: 'Tanzania', language: 'en', phonePrefix: '255' },
    { code: 'TG', name: 'Togo', language: 'fr', phonePrefix: '228' },
    { code: 'TN', name: 'Tunisia', language: 'fr', phonePrefix: '216' },
    { code: 'UG', name: 'Uganda', language: 'en', phonePrefix: '256' },
    { code: 'EH', name: 'Western Sahara', language: 'fr', phonePrefix: '212' },
    { code: 'ZM', name: 'Zambia', language: 'en', phonePrefix: '260' },
    { code: 'ZW', name: 'Zimbabwe', language: 'en', phonePrefix: '263' },

    // Asie
    { code: 'AF', name: 'Afghanistan', language: 'en', phonePrefix: '93' },
    { code: 'AM', name: 'Armenia', language: 'en', phonePrefix: '374' },
    { code: 'AZ', name: 'Azerbaijan', language: 'en', phonePrefix: '994' },
    { code: 'BH', name: 'Bahrain', language: 'en', phonePrefix: '973' },
    { code: 'BD', name: 'Bangladesh', language: 'en', phonePrefix: '880' },
    { code: 'BT', name: 'Bhutan', language: 'en', phonePrefix: '975' },
    { code: 'BN', name: 'Brunei', language: 'en', phonePrefix: '673' },
    { code: 'KH', name: 'Cambodia', language: 'en', phonePrefix: '855' },
    { code: 'CN', name: 'China', language: 'en', phonePrefix: '86' },
    { code: 'CY', name: 'Cyprus', language: 'en', phonePrefix: '357' },
    { code: 'GE', name: 'Georgia', language: 'en', phonePrefix: '995' },
    { code: 'HK', name: 'Hong Kong', language: 'en', phonePrefix: '852' },
    { code: 'IN', name: 'India', language: 'en', phonePrefix: '91' },
    { code: 'ID', name: 'Indonesia', language: 'en', phonePrefix: '62' },
    { code: 'IR', name: 'Iran', language: 'en', phonePrefix: '98' },
    { code: 'IQ', name: 'Iraq', language: 'en', phonePrefix: '964' },
    { code: 'IL', name: 'Israel', language: 'en', phonePrefix: '972' },
    { code: 'JP', name: 'Japan', language: 'en', phonePrefix: '81' },
    { code: 'JO', name: 'Jordan', language: 'en', phonePrefix: '962' },
    { code: 'KZ', name: 'Kazakhstan', language: 'en', phonePrefix: '7' },
    { code: 'KW', name: 'Kuwait', language: 'en', phonePrefix: '965' },
    { code: 'KG', name: 'Kyrgyzstan', language: 'en', phonePrefix: '996' },
    { code: 'LA', name: 'Laos', language: 'en', phonePrefix: '856' },
    { code: 'LB', name: 'Lebanon', language: 'en', phonePrefix: '961' },
    { code: 'MO', name: 'Macao', language: 'en', phonePrefix: '853' },
    { code: 'MY', name: 'Malaysia', language: 'en', phonePrefix: '60' },
    { code: 'MV', name: 'Maldives', language: 'en', phonePrefix: '960' },
    { code: 'MN', name: 'Mongolia', language: 'en', phonePrefix: '976' },
    { code: 'MM', name: 'Myanmar', language: 'en', phonePrefix: '95' },
    { code: 'NP', name: 'Nepal', language: 'en', phonePrefix: '977' },
    { code: 'KP', name: 'North Korea', language: 'en', phonePrefix: '850' },
    { code: 'OM', name: 'Oman', language: 'en', phonePrefix: '968' },
    { code: 'PK', name: 'Pakistan', language: 'en', phonePrefix: '92' },
    { code: 'PS', name: 'Palestine', language: 'en', phonePrefix: '970' },
    { code: 'PH', name: 'Philippines', language: 'en', phonePrefix: '63' },
    { code: 'QA', name: 'Qatar', language: 'en', phonePrefix: '974' },
    { code: 'SA', name: 'Saudi Arabia', language: 'en', phonePrefix: '966' },
    { code: 'SG', name: 'Singapore', language: 'en', phonePrefix: '65' },
    { code: 'KR', name: 'South Korea', language: 'en', phonePrefix: '82' },
    { code: 'LK', name: 'Sri Lanka', language: 'en', phonePrefix: '94' },
    { code: 'SY', name: 'Syria', language: 'en', phonePrefix: '963' },
    { code: 'TW', name: 'Taiwan', language: 'en', phonePrefix: '886' },
    { code: 'TJ', name: 'Tajikistan', language: 'en', phonePrefix: '992' },
    { code: 'TH', name: 'Thailand', language: 'en', phonePrefix: '66' },
    { code: 'TL', name: 'Timor-Leste', language: 'en', phonePrefix: '670' },
    { code: 'TR', name: 'Turkey', language: 'en', phonePrefix: '90' },
    { code: 'TM', name: 'Turkmenistan', language: 'en', phonePrefix: '993' },
    { code: 'AE', name: 'United Arab Emirates', language: 'en', phonePrefix: '971' },
    { code: 'UZ', name: 'Uzbekistan', language: 'en', phonePrefix: '998' },
    { code: 'VN', name: 'Vietnam', language: 'en', phonePrefix: '84' },
    { code: 'YE', name: 'Yemen', language: 'en', phonePrefix: '967' },

    // Europe
    { code: 'AL', name: 'Albania', language: 'en', phonePrefix: '355' },
    { code: 'AD', name: 'Andorra', language: 'fr', phonePrefix: '376' },
    { code: 'AT', name: 'Austria', language: 'en', phonePrefix: '43' },
    { code: 'BY', name: 'Belarus', language: 'en', phonePrefix: '375' },
    { code: 'BE', name: 'Belgium', language: 'fr', phonePrefix: '32' },
    { code: 'BA', name: 'Bosnia and Herzegovina', language: 'en', phonePrefix: '387' },
    { code: 'BG', name: 'Bulgaria', language: 'en', phonePrefix: '359' },
    { code: 'HR', name: 'Croatia', language: 'en', phonePrefix: '385' },
    { code: 'CZ', name: 'Czech Republic', language: 'en', phonePrefix: '420' },
    { code: 'DK', name: 'Denmark', language: 'en', phonePrefix: '45' },
    { code: 'EE', name: 'Estonia', language: 'en', phonePrefix: '372' },
    { code: 'FO', name: 'Faroe Islands', language: 'en', phonePrefix: '298' },
    { code: 'FI', name: 'Finland', language: 'en', phonePrefix: '358' },
    { code: 'FR', name: 'France', language: 'fr', phonePrefix: '33' },
    { code: 'DE', name: 'Germany', language: 'en', phonePrefix: '49' },
    { code: 'GI', name: 'Gibraltar', language: 'en', phonePrefix: '350' },
    { code: 'GR', name: 'Greece', language: 'en', phonePrefix: '30' },
    { code: 'GL', name: 'Greenland', language: 'en', phonePrefix: '299' },
    { code: 'GG', name: 'Guernsey', language: 'en', phonePrefix: '44' },
    { code: 'HU', name: 'Hungary', language: 'en', phonePrefix: '36' },
    { code: 'IS', name: 'Iceland', language: 'en', phonePrefix: '354' },
    { code: 'IE', name: 'Ireland', language: 'en', phonePrefix: '353' },
    { code: 'IM', name: 'Isle of Man', language: 'en', phonePrefix: '44' },
    { code: 'IT', name: 'Italy', language: 'en', phonePrefix: '39' },
    { code: 'JE', name: 'Jersey', language: 'en', phonePrefix: '44' },
    { code: 'XK', name: 'Kosovo', language: 'en', phonePrefix: '383' },
    { code: 'LV', name: 'Latvia', language: 'en', phonePrefix: '371' },
    { code: 'LI', name: 'Liechtenstein', language: 'en', phonePrefix: '423' },
    { code: 'LT', name: 'Lithuania', language: 'en', phonePrefix: '370' },
    { code: 'LU', name: 'Luxembourg', language: 'fr', phonePrefix: '352' },
    { code: 'MT', name: 'Malta', language: 'en', phonePrefix: '356' },
    { code: 'MD', name: 'Moldova', language: 'en', phonePrefix: '373' },
    { code: 'MC', name: 'Monaco', language: 'fr', phonePrefix: '377' },
    { code: 'ME', name: 'Montenegro', language: 'en', phonePrefix: '382' },
    { code: 'NL', name: 'Netherlands', language: 'en', phonePrefix: '31' },
    { code: 'MK', name: 'North Macedonia', language: 'en', phonePrefix: '389' },
    { code: 'NO', name: 'Norway', language: 'en', phonePrefix: '47' },
    { code: 'PL', name: 'Poland', language: 'en', phonePrefix: '48' },
    { code: 'PT', name: 'Portugal', language: 'en', phonePrefix: '351' },
    { code: 'RO', name: 'Romania', language: 'en', phonePrefix: '40' },
    { code: 'RU', name: 'Russia', language: 'en', phonePrefix: '7' },
    { code: 'SM', name: 'San Marino', language: 'en', phonePrefix: '378' },
    { code: 'RS', name: 'Serbia', language: 'en', phonePrefix: '381' },
    { code: 'SK', name: 'Slovakia', language: 'en', phonePrefix: '421' },
    { code: 'SI', name: 'Slovenia', language: 'en', phonePrefix: '386' },
    { code: 'ES', name: 'Spain', language: 'en', phonePrefix: '34' },
    { code: 'SJ', name: 'Svalbard and Jan Mayen', language: 'en', phonePrefix: '47' },
    { code: 'SE', name: 'Sweden', language: 'en', phonePrefix: '46' },
    { code: 'CH', name: 'Switzerland', language: 'fr', phonePrefix: '41' },
    { code: 'UA', name: 'Ukraine', language: 'en', phonePrefix: '380' },
    { code: 'GB', name: 'United Kingdom', language: 'en', phonePrefix: '44' },
    { code: 'VA', name: 'Vatican City', language: 'en', phonePrefix: '379' },

    // Amérique du Nord
    { code: 'CA', name: 'Canada', language: 'en', phonePrefix: '1' },
    { code: 'GL', name: 'Greenland', language: 'en', phonePrefix: '299' },
    { code: 'MX', name: 'Mexico', language: 'en', phonePrefix: '52' },
    { code: 'PM', name: 'Saint Pierre and Miquelon', language: 'fr', phonePrefix: '508' },
    { code: 'US', name: 'United States', language: 'en', phonePrefix: '1' },

    // Amérique Centrale
    { code: 'BZ', name: 'Belize', language: 'en', phonePrefix: '501' },
    { code: 'CR', name: 'Costa Rica', language: 'en', phonePrefix: '506' },
    { code: 'SV', name: 'El Salvador', language: 'en', phonePrefix: '503' },
    { code: 'GT', name: 'Guatemala', language: 'en', phonePrefix: '502' },
    { code: 'HN', name: 'Honduras', language: 'en', phonePrefix: '504' },
    { code: 'NI', name: 'Nicaragua', language: 'en', phonePrefix: '505' },
    { code: 'PA', name: 'Panama', language: 'en', phonePrefix: '507' },

    // Amérique du Sud
    { code: 'AR', name: 'Argentina', language: 'en', phonePrefix: '54' },
    { code: 'BO', name: 'Bolivia', language: 'en', phonePrefix: '591' },
    { code: 'BR', name: 'Brazil', language: 'en', phonePrefix: '55' },
    { code: 'CL', name: 'Chile', language: 'en', phonePrefix: '56' },
    { code: 'CO', name: 'Colombia', language: 'en', phonePrefix: '57' },
    { code: 'EC', name: 'Ecuador', language: 'en', phonePrefix: '593' },
    { code: 'FK', name: 'Falkland Islands', language: 'en', phonePrefix: '500' },
    { code: 'GF', name: 'French Guiana', language: 'fr', phonePrefix: '594' },
    { code: 'GY', name: 'Guyana', language: 'en', phonePrefix: '592' },
    { code: 'PY', name: 'Paraguay', language: 'en', phonePrefix: '595' },
    { code: 'PE', name: 'Peru', language: 'en', phonePrefix: '51' },
    { code: 'SR', name: 'Suriname', language: 'en', phonePrefix: '597' },
    { code: 'UY', name: 'Uruguay', language: 'en', phonePrefix: '598' },
    { code: 'VE', name: 'Venezuela', language: 'en', phonePrefix: '58' },

    // Caraïbes
    { code: 'AI', name: 'Anguilla', language: 'en', phonePrefix: '1' },
    { code: 'AG', name: 'Antigua and Barbuda', language: 'en', phonePrefix: '1' },
    { code: 'AW', name: 'Aruba', language: 'en', phonePrefix: '297' },
    { code: 'BS', name: 'Bahamas', language: 'en', phonePrefix: '1' },
    { code: 'BB', name: 'Barbados', language: 'en', phonePrefix: '1' },
    { code: 'BM', name: 'Bermuda', language: 'en', phonePrefix: '1' },
    { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', language: 'en', phonePrefix: '599' },
    { code: 'VG', name: 'British Virgin Islands', language: 'en', phonePrefix: '1' },
    { code: 'KY', name: 'Cayman Islands', language: 'en', phonePrefix: '1' },
    { code: 'CU', name: 'Cuba', language: 'en', phonePrefix: '53' },
    { code: 'CW', name: 'Curaçao', language: 'en', phonePrefix: '599' },
    { code: 'DM', name: 'Dominica', language: 'en', phonePrefix: '1' },
    { code: 'DO', name: 'Dominican Republic', language: 'en', phonePrefix: '1' },
    { code: 'GD', name: 'Grenada', language: 'en', phonePrefix: '1' },
    { code: 'GP', name: 'Guadeloupe', language: 'fr', phonePrefix: '590' },
    { code: 'HT', name: 'Haiti', language: 'fr', phonePrefix: '509' },
    { code: 'JM', name: 'Jamaica', language: 'en', phonePrefix: '1' },
    { code: 'MQ', name: 'Martinique', language: 'fr', phonePrefix: '596' },
    { code: 'MS', name: 'Montserrat', language: 'en', phonePrefix: '1' },
    { code: 'PR', name: 'Puerto Rico', language: 'en', phonePrefix: '1' },
    { code: 'BL', name: 'Saint Barthélemy', language: 'fr', phonePrefix: '590' },
    { code: 'KN', name: 'Saint Kitts and Nevis', language: 'en', phonePrefix: '1' },
    { code: 'LC', name: 'Saint Lucia', language: 'en', phonePrefix: '1' },
    { code: 'MF', name: 'Saint Martin', language: 'fr', phonePrefix: '590' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', language: 'en', phonePrefix: '1' },
    { code: 'SX', name: 'Sint Maarten', language: 'en', phonePrefix: '1' },
    { code: 'TT', name: 'Trinidad and Tobago', language: 'en', phonePrefix: '1' },
    { code: 'TC', name: 'Turks and Caicos Islands', language: 'en', phonePrefix: '1' },
    { code: 'VI', name: 'US Virgin Islands', language: 'en', phonePrefix: '1' },

    // Océanie
    { code: 'AU', name: 'Australia', language: 'en', phonePrefix: '61' },
    { code: 'CK', name: 'Cook Islands', language: 'en', phonePrefix: '682' },
    { code: 'FJ', name: 'Fiji', language: 'en', phonePrefix: '679' },
    { code: 'PF', name: 'French Polynesia', language: 'fr', phonePrefix: '689' },
    { code: 'GU', name: 'Guam', language: 'en', phonePrefix: '1' },
    { code: 'KI', name: 'Kiribati', language: 'en', phonePrefix: '686' },
    { code: 'MH', name: 'Marshall Islands', language: 'en', phonePrefix: '692' },
    { code: 'FM', name: 'Micronesia', language: 'en', phonePrefix: '691' },
    { code: 'NR', name: 'Nauru', language: 'en', phonePrefix: '674' },
    { code: 'NC', name: 'New Caledonia', language: 'fr', phonePrefix: '687' },
    { code: 'NZ', name: 'New Zealand', language: 'en', phonePrefix: '64' },
    { code: 'NU', name: 'Niue', language: 'en', phonePrefix: '683' },
    { code: 'NF', name: 'Norfolk Island', language: 'en', phonePrefix: '672' },
    { code: 'MP', name: 'Northern Mariana Islands', language: 'en', phonePrefix: '1' },
    { code: 'PW', name: 'Palau', language: 'en', phonePrefix: '680' },
    { code: 'PG', name: 'Papua New Guinea', language: 'en', phonePrefix: '675' },
    { code: 'PN', name: 'Pitcairn Islands', language: 'en', phonePrefix: '872' },
    { code: 'WS', name: 'Samoa', language: 'en', phonePrefix: '685' },
    { code: 'SB', name: 'Solomon Islands', language: 'en', phonePrefix: '677' },
    { code: 'TK', name: 'Tokelau', language: 'en', phonePrefix: '690' },
    { code: 'TO', name: 'Tonga', language: 'en', phonePrefix: '676' },
    { code: 'TV', name: 'Tuvalu', language: 'en', phonePrefix: '688' },
    { code: 'VU', name: 'Vanuatu', language: 'en', phonePrefix: '678' },
    { code: 'WF', name: 'Wallis and Futuna', language: 'fr', phonePrefix: '681' },

    // Antarctique
    { code: 'AQ', name: 'Antarctica', language: 'en', phonePrefix: '672' },
    { code: 'BV', name: 'Bouvet Island', language: 'en', phonePrefix: '47' },
    { code: 'GS', name: 'South Georgia and the South Sandwich Islands', language: 'en', phonePrefix: '500' },
    { code: 'HM', name: 'Heard Island and McDonald Islands', language: 'en', phonePrefix: '672' },
    { code: 'TF', name: 'French Southern Territories', language: 'fr', phonePrefix: '262' },

    // Autres territoires
    { code: 'AS', name: 'American Samoa', language: 'en', phonePrefix: '1' },
    { code: 'CC', name: 'Cocos (Keeling) Islands', language: 'en', phonePrefix: '61' },
    { code: 'CX', name: 'Christmas Island', language: 'en', phonePrefix: '61' },
    { code: 'IO', name: 'British Indian Ocean Territory', language: 'en', phonePrefix: '246' },
    { code: 'UM', name: 'United States Minor Outlying Islands', language: 'en', phonePrefix: '1' },
];